project:
  type: website
  output-dir: docs

website:
  title: "Coding Resources"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: "Tips"
        menu:
        - href: tips/github.qmd
          text: Installing git & github
      - text: "Data"
        menu:
        - href: data/species_data.qmd
          text: Acquiring species data
        - href: data/cmi.qmd
          text: Climate moisture index
        - href: data/climatena.qmd
          text: Getting climate data
      - text: "Stats"
        menu:
        - href: stats/occurrence.qmd
          text: Species distribution modelling
      - href: resources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true