project:
  type: website
  output-dir: docs

website:
  title: "Coding Resources"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: "Tips"
        menu:
        - href: tips/github.qmd
          text: Installing git & github
        - href: tips/species_data.qmd
          text: Acquiring species data
      - text: "Tutorials"
        menu:
        - href: tutorials/occurrence.qmd
          text: Species distribution modelling
      - href: resources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true